
window.mockMovies = [
  {
    "Title": "Inception",
    "Year": "2010",
    "Rated": "PG-13",
    "Released": "16 Jul 2010",
    "Runtime": "148 min",
    "Genre": "Action, Sci-Fi, Adventure",
    "Director": "Christopher Nolan",
    "Writer": "Christopher Nolan",
    "Actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
    "Plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    "Language": "English, Japanese, French",
    "Country": "United States, United Kingdom",
    "Awards": "Won 4 Oscars. 158 wins & 220 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "8.8/10" },
      { "Source": "Rotten Tomatoes", "Value": "87%" },
      { "Source": "Metacritic", "Value": "74/100" }
    ],
    "Metascore": "74",
    "imdbRating": "8.8",
    "imdbVotes": "2,564,213",
    "imdbID": "tt1375666",
    "Type": "movie"
  },
  {
    "Title": "The Dark Knight",
    "Year": "2008",
    "Rated": "PG-13",
    "Released": "18 Jul 2008",
    "Runtime": "152 min",
    "Genre": "Action, Crime, Drama",
    "Director": "Christopher Nolan",
    "Writer": "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    "Actors": "Christian Bale, Heath Ledger, Aaron Eckhart, Maggie Gyllenhaal",
    "Plot": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    "Language": "English, Mandarin",
    "Country": "United States, United Kingdom",
    "Awards": "Won 2 Oscars. 163 wins & 164 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "9.0/10" },
      { "Source": "Rotten Tomatoes", "Value": "94%" },
      { "Source": "Metacritic", "Value": "84/100" }
    ],
    "Metascore": "84",
    "imdbRating": "9.0",
    "imdbVotes": "2,875,190",
    "imdbID": "tt0468569",
    "Type": "movie"
  },
  {
    "Title": "Interstellar",
    "Year": "2014",
    "Rated": "PG-13",
    "Released": "07 Nov 2014",
    "Runtime": "169 min",
    "Genre": "Adventure, Drama, Sci-Fi",
    "Director": "Christopher Nolan",
    "Writer": "Jonathan Nolan, Christopher Nolan",
    "Actors": "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Mackenzie Foy",
    "Plot": "When Earth becomes uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
    "Language": "English",
    "Country": "United States, United Kingdom, Canada",
    "Awards": "Won 1 Oscar. 44 wins & 148 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYl5hZDY5YWQtNWQyZi00MTYyLThiNzUtY2ExMDU1ZTUyZDgyXkEyXkFqcGdeQXVyMTAyOTE4NjE0._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "8.7/10" },
      { "Source": "Rotten Tomatoes", "Value": "73%" },
      { "Source": "Metacritic", "Value": "74/100" }
    ],
    "Metascore": "74",
    "imdbRating": "8.7",
    "imdbVotes": "2,056,233",
    "imdbID": "tt0816692",
    "Type": "movie"
  },
  {
    "Title": "Spirited Away",
    "Year": "2001",
    "Rated": "PG",
    "Released": "28 Mar 2003",
    "Runtime": "125 min",
    "Genre": "Animation, Adventure, Family, Fantasy",
    "Director": "Hayao Miyazaki",
    "Writer": "Hayao Miyazaki",
    "Actors": "Daveigh Chase, Suzanne Pleshette, Jason Marsden, Susan Egan",
    "Plot": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    "Language": "Japanese",
    "Country": "Japan",
    "Awards": "Won 1 Oscar. 57 wins & 31 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZmItOTVlYzMyMDRmYWU3XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "8.6/10" },
      { "Source": "Rotten Tomatoes", "Value": "96%" },
      { "Source": "Metacritic", "Value": "96/100" }
    ],
    "Metascore": "96",
    "imdbRating": "8.6",
    "imdbVotes": "834,128",
    "imdbID": "tt0245429",
    "Type": "movie"
  },
  {
    "Title": "Pulp Fiction",
    "Year": "1994",
    "Rated": "R",
    "Released": "14 Oct 1994",
    "Runtime": "154 min",
    "Genre": "Crime, Drama",
    "Director": "Quentin Tarantino",
    "Writer": "Quentin Tarantino, Roger Avary",
    "Actors": "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis",
    "Plot": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    "Language": "English, Spanish, French",
    "Country": "United States",
    "Awards": "Won 1 Oscar. 70 wins & 75 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYTViYjY3ZGQtNDFjNi00NGRjLTg0YTUtNDc4YzFlMDc2MDc2XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "8.9/10" },
      { "Source": "Rotten Tomatoes", "Value": "92%" },
      { "Source": "Metacritic", "Value": "95/100" }
    ],
    "Metascore": "95",
    "imdbRating": "8.9",
    "imdbVotes": "2,204,912",
    "imdbID": "tt0110912",
    "Type": "movie"
  },
  {
    "Title": "Spider-Man: Into the Spider-Verse",
    "Year": "2018",
    "Rated": "PG",
    "Released": "14 Dec 2018",
    "Runtime": "117 min",
    "Genre": "Animation, Action, Adventure, Family, Sci-Fi",
    "Director": "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    "Writer": "Phil Lord, Rodney Rothman",
    "Actors": "Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali",
    "Plot": "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    "Language": "English, Spanish",
    "Country": "United States",
    "Awards": "Won 1 Oscar. 85 wins & 59 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTcwNTkwNTQyOA@@._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "8.4/10" },
      { "Source": "Rotten Tomatoes", "Value": "97%" },
      { "Source": "Metacritic", "Value": "87/100" }
    ],
    "Metascore": "87",
    "imdbRating": "8.4",
    "imdbVotes": "642,891",
    "imdbID": "tt4633694",
    "Type": "movie"
  },
  {
    "Title": "Parasite",
    "Year": "2019",
    "Rated": "R",
    "Released": "08 Nov 2019",
    "Runtime": "132 min",
    "Genre": "Drama, Thriller",
    "Director": "Bong Joon Ho",
    "Writer": "Bong Joon Ho, Jin Won Han",
    "Actors": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-sik",
    "Plot": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    "Language": "Korean, English",
    "Country": "South Korea",
    "Awards": "Won 4 Oscars. 312 wins & 267 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "8.5/10" },
      { "Source": "Rotten Tomatoes", "Value": "99%" },
      { "Source": "Metacritic", "Value": "96/100" }
    ],
    "Metascore": "96",
    "imdbRating": "8.5",
    "imdbVotes": "921,432",
    "imdbID": "tt6751668",
    "Type": "movie"
  },
  {
    "Title": "The Matrix",
    "Year": "1999",
    "Rated": "R",
    "Released": "31 Mar 1999",
    "Runtime": "136 min",
    "Genre": "Action, Sci-Fi",
    "Director": "Lana Wachowski, Lilly Wachowski",
    "Writer": "Lana Wachowski, Lilly Wachowski",
    "Actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
    "Plot": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    "Language": "English",
    "Country": "United States, Australia",
    "Awards": "Won 4 Oscars. 42 wins & 52 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDkyZGQ1MDFmNWRiXkEyXkFqcGdeQXVyNjU0OTQ0OTY._V1_SX300.jpg",
    "Ratings": [
      { "Source": "Internet Movie Database", "Value": "8.7/10" },
      { "Source": "Rotten Tomatoes", "Value": "83%" },
      { "Source": "Metacritic", "Value": "73/100" }
    ],
    "Metascore": "73",
    "imdbRating": "8.7",
    "imdbVotes": "2,023,892",
    "imdbID": "tt0133093",
    "Type": "movie"
  }
];
